import { Bouquet } from '../services/bouquet.service';

// The original demo catalog, used only to seed a fresh/empty Firestore project. Once
// seeded, the live BouquetService reads from Firestore, not from this file.
export const SEED_BOUQUETS: Omit<Bouquet, 'id' | 'status' | 'deleted' | 'composition' | 'createdAt'>[] = [
  {
    name: 'Для найкращої мами',
    subtitle: 'На день народження, 8 березня або просто так — бо мама завжди заслуговує на квіти.',
    price: 850,
    photo: 'https://images.unsplash.com/photo-1623406795110-99f1c4325084?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Ym91cXVldCUyMGZvciUyMG1vbXxlbnwwfHwwfHx8MA%3D%3D',
    occasion: 'birthday',
    type: 'roses',
    color: 'pink',
    tag: 'Хіт',
    tagTone: 'pink',
    tags: ['birthday', 'gentle', 'mid'],
  },
  {
    name: 'В любові по вуха',
    subtitle: 'Коли слова застрягають у горлі, а серце готове вибухнути. Для того хто зробив тебе щасливим.',
    price: 1200,
    photo: 'https://images.unsplash.com/photo-1620142828449-203a4979d9c3?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Ym91cXVldCUyMG9mJTIwcmVkJTIwZmxvd2Vyc3xlbnwwfHwwfHx8MA%3D%3D',
    occasion: 'anniversary',
    type: 'roses',
    color: 'red',
    tags: ['anniversary', 'romantic', 'premium'],
  },
  {
    name: 'Без приводу, просто так',
    subtitle: 'Найкращий подарунок — той якого не чекають. Для людини яку хочеться порадувати без жодної причини.',
    price: 950,
    photo: 'https://plus.unsplash.com/premium_photo-1661659745326-d2535dfd268c?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHx8',
    occasion: 'justbecause',
    type: 'mixed',
    color: 'teal',
    tag: 'Сезонне',
    tagTone: 'teal',
    tags: ['justbecause', 'calm', 'mid'],
  },
  {
    name: "Коли настрій кращий за погоду",
    subtitle: "Для святкування маленьких перемог, гарних новин або просто вдалого дня що хочеться запам'ятати.",
    price: 780,
    photo: 'https://images.unsplash.com/photo-1679502460180-f9f0c75267c2?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    occasion: 'birthday',
    type: 'mixed',
    color: 'yellow',
    tags: ['birthday', 'bright', 'fun', 'mid'],
  },
  {
    name: 'Коли серце завмирає',
    subtitle: 'На річницю, весілля або коли хочеш нагадати коханій людині що почуття нікуди не зникли.',
    price: 1450,
    photo: 'https://images.unsplash.com/photo-1678043639749-fb3c5c0314ce?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDM3fHx8ZW58MHx8fHx8',
    occasion: 'anniversary',
    type: 'mixed',
    color: 'pink',
    tags: ['anniversary', 'romantic', 'premium'],
  },
  {
    name: 'Без причини — це і є причина',
    subtitle: 'Бо іноді найважливіше — просто показати що думаєш про людину. Без свят і приводів.',
    price: 690,
    photo: 'https://images.unsplash.com/photo-1584798962082-790d3f40fa04?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDcxfHx8ZW58MHx8fHx8',
    occasion: 'justbecause',
    type: 'mixed',
    color: 'green',
    tags: ['justbecause', 'calm', 'budget'],
  },
  {
    name: 'Для тих хто мріє',
    subtitle: 'Для людини яка завжди дивиться трохи далі горизонту. На підтримку, натхнення або великий крок вперед.',
    price: 1100,
    photo: 'https://plus.unsplash.com/premium_photo-1678115816034-8bce8ae163af?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDgwfHx8ZW58MHx8fHx8',
    occasion: 'support',
    type: 'mixed',
    color: 'purple',
    tags: ['elegant', 'premium'],
  },
  {
    name: 'Хочу справити враження',
    subtitle: 'Для першого побачення, важливої зустрічі або моменту коли хочеться щоб тебе запам\'ятали.',
    price: 990,
    photo: 'https://plus.unsplash.com/premium_photo-1668073436953-492767f88b8d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Ym91cXVldCUyMG9mJTIwYmx1ZSUyMGZsb3dlcnN8ZW58MHx8MHx8fDA%3D',
    occasion: 'date',
    type: 'roses',
    color: 'pink',
    tag: 'Новинка',
    tagTone: 'spark',
    tags: ['date', 'romantic', 'mid'],
  },
  {
    name: 'Спасибі, що ти поруч',
    subtitle: 'Для людини яка була поруч коли було важко. Бо «дякую» іноді треба говорити квітами.',
    price: 720,
    photo: 'https://images.unsplash.com/photo-1678043639841-0dd13f8b1f1b?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDg2fHx8ZW58MHx8fHx8',
    occasion: 'thankyou',
    type: 'mixed',
    color: 'yellow',
    tags: ['thankyou', 'gentle', 'mid'],
  },
  {
    name: 'Слова скінчились — залишились квіти',
    subtitle: 'Коли посварились і не знаєш з чого почати. Квіти скажуть те що важко вимовити вголос.',
    price: 880,
    photo: 'https://images.unsplash.com/photo-1554742896-b3b354bd59f0?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDM1fHx8ZW58MHx8fHx8',
    occasion: 'sorry',
    type: 'roses',
    color: 'pink',
    tags: ['sorry', 'gentle', 'mid'],
  },
  {
    name: 'Троянди класичні',
    subtitle: 'Вічна класика для тих хто цінує традиції.',
    price: 1100,
    photo: 'https://plus.unsplash.com/premium_photo-1677005659579-dfdefd6e6c09?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    occasion: 'anniversary',
    type: 'roses',
    color: 'red',
    tags: ['anniversary', 'romantic', 'premium'],
  },
  {
    name: 'Тюльпани весняні',
    subtitle: 'Свіжість весни у кожній пелюстці.',
    price: 650,
    photo: 'https://images.unsplash.com/photo-1589994160839-163cd867cfe8?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJvdXF1ZXQlMjBvZiUyMHR1bGlwc3xlbnwwfHwwfHx8MA%3D%3D',
    occasion: 'birthday',
    type: 'tulips',
    color: 'pink',
    tags: ['birthday', 'gentle', 'budget'],
  },
  {
    name: 'Соняхи яскраві',
    subtitle: 'Тепло і радість — як сонце в букеті.',
    price: 720,
    photo: 'https://plus.unsplash.com/premium_photo-1676692121474-a3e3890d39f4?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    occasion: 'justbecause',
    type: 'sunflowers',
    color: 'yellow',
    tags: ['justbecause', 'bright', 'fun', 'mid'],
  },
  {
    name: 'Півонії ніжні',
    subtitle: "М'якість і розкіш для особливого моменту.",
    price: 1350,
    photo: 'https://images.unsplash.com/photo-1560583035-657b74826ec9?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D',
    occasion: 'wedding',
    type: 'peonies',
    color: 'pink',
    tags: ['anniversary', 'romantic', 'elegant', 'premium'],
  },
  {
    name: 'Лаванда прованс',
    subtitle: 'Спокій і аромат французького Провансу.',
    price: 890,
    photo: 'https://images.unsplash.com/photo-1635692027511-bea646416e86?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGJvdXF1ZXQlMjBvZiUyMGxhdmFuZGVyfGVufDB8fDB8fHww',
    occasion: 'thankyou',
    type: 'lavender',
    color: 'purple',
    tags: ['thankyou', 'calm', 'elegant', 'mid'],
  },
  {
    name: 'Хризантеми білі',
    subtitle: 'Чистота і елегантність у кожній квітці.',
    price: 780,
    photo: 'https://images.unsplash.com/photo-1767797285478-ad1c6241c839?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    occasion: 'support',
    type: 'chrysanthemums',
    color: 'white',
    tags: ['calm', 'elegant', 'mid'],
  },
  {
    name: 'Орхідеї преміум',
    subtitle: 'Вишуканість для тих хто цінує красу.',
    price: 1800,
    photo: 'https://images.unsplash.com/photo-1729603369767-3d151219fe75?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8',
    occasion: 'anniversary',
    type: 'orchids',
    color: 'white',
    tag: 'Преміум',
    tagTone: 'pink',
    tags: ['anniversary', 'elegant', 'luxury'],
  },
  {
    name: 'Польові квіти',
    subtitle: 'Натуральна краса лугів і полів.',
    price: 590,
    photo: 'https://images.unsplash.com/photo-1596238276574-b3e8d40fbafb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Ym91cXVldCUyMG9mJTIwd2lsZGZsb3dlcnN8ZW58MHx8MHx8fDA%3D',
    occasion: 'justbecause',
    type: 'wildflowers',
    color: 'mixed',
    tags: ['justbecause', 'bright', 'fun', 'budget'],
  },
  {
    name: 'Гербери сонячні',
    subtitle: 'Яскравість і позитив на весь день.',
    price: 680,
    photo: 'https://plus.unsplash.com/premium_photo-1692394464308-5f876cfbae69?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Ym91cXVldCUyMG9mJTIwYnJpZ2h0JTIwZmxvd2Vyc3xlbnwwfHwwfHx8MA%3D%3D',
    occasion: 'birthday',
    type: 'gerberas',
    color: 'orange',
    tags: ['birthday', 'bright', 'fun', 'budget'],
  },
  {
    name: 'Лілії білі',
    subtitle: 'Ніжний аромат і чиста елегантність.',
    price: 950,
    photo: 'https://images.unsplash.com/photo-1772211505818-c15eecf8e3c9?q=80&w=790&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    occasion: 'wedding',
    type: 'lilies',
    color: 'white',
    tags: ['elegant', 'calm', 'mid'],
  },
];
